trabajo/theprettystore/config/routes.rb
Rails.application.routes.draw do
  resources :listados

  get 'pages/sobre'

  get 'pages/contacto'
  root 'listados#index'

end

trabajo/theprettystore/app/models/listado.rb
class Listado < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "default.jpg"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

trabajo/theprettystore/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

trabajo/theprettystore/app/controllers/listados_controller.rb
class ListadosController < ApplicationController
  before_action :set_listado, only: [:show, :edit, :update, :destroy]

  # GET /listados
  # GET /listados.json
  def index
    @listados = Listado.all
  end

  # GET /listados/1
  # GET /listados/1.json
  def show
  end

  # GET /listados/new
  def new
    @listado = Listado.new
  end

  # GET /listados/1/edit
  def edit
  end

  # POST /listados
  # POST /listados.json
  def create
    @listado = Listado.new(listado_params)

    respond_to do |format|
      if @listado.save
        format.html { redirect_to @listado, notice: 'Listado was successfully created.' }
        format.json { render :show, status: :created, location: @listado }
      else
        format.html { render :new }
        format.json { render json: @listado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listados/1
  # PATCH/PUT /listados/1.json
  def update
    respond_to do |format|
      if @listado.update(listado_params)
        format.html { redirect_to @listado, notice: 'Listado was successfully updated.' }
        format.json { render :show, status: :ok, location: @listado }
      else
        format.html { render :edit }
        format.json { render json: @listado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listados/1
  # DELETE /listados/1.json
  def destroy
    @listado.destroy
    respond_to do |format|
      format.html { redirect_to listados_url, notice: 'Listado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listado
      @listado = Listado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listado_params
      params.require(:listado).permit(:name, :description, :price, :image)
    end

end

trabajo/theprettystore/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def sobre
  end

  def contacto
  end
end

trabajo/theprettystore/app/helpers/application_helper.rb
module ApplicationHelper
end

trabajo/theprettystore/app/helpers/listados_helper.rb
module ListadosHelper
end

trabajo/theprettystore/app/helpers/pages_helper.rb
module PagesHelper
end

trabajo/theprettystore/app/views/layouts/_footer.html.erb
<p>Copyright 2015</p>

trabajo/theprettystore/app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="#">The Pretty Store</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/pages/sobre/">Sobre</a></li>
        <li><a href="/pages/contacto/">Contacto</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

trabajo/theprettystore/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Theprettystore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

    <div class="container">
        <%= yield %>
        <%= render 'layouts/footer' %>
    </div>
</body>
</html>

trabajo/theprettystore/app/views/listados/_form.html.erb
<%= image_tag @listado.image.url(:medium) %>



<%= form_for(@listado, :html => { :multipart => true })  do |f| %>

  <% if @listado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listado.errors.count, "error") %> prohibited this listado from being saved:</h2>

      <ul>
      <% @listado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, class:'form-control'%>
  </div>
    <div class="form-group">
        <%= f.file_field :image, class:'form-control' %>
    </div>
  <div class="actions">
    <%= f.submit class:'btn btn-primary' %>
  </div>
<% end %>

trabajo/theprettystore/app/views/listados/edit.html.erb
<h1>Editing Listado</h1>

<%= render 'form' %>

<%= link_to 'Show', @listado, class:'btn btn-link' %> |
<%= link_to 'Back', listados_path, class:'btn btn-link' %>

trabajo/theprettystore/app/views/listados/index.html.erb
<div class="center">

        <div class="row">
          <% @listados.each do |listado| %>
              <div class="col-md-3">

                <div class="thumbnail">
                  <%= image_tag (listado.image.url(:medium)) %>
                  <div class="caption">
                    <h3><%= listado.name %></h3>
                    <p><%= number_to_currency(listado.price, :unit => " € ") %></p>
                    <%= link_to 'Show', listado, class:'btn btn-link' %>
                    <%= link_to 'Edit', edit_listado_path(listado), class:'btn btn-link' %>
                    <%= link_to 'Destroy', listado, class:'btn btn-link', method: :delete, data: { confirm: 'Are you sure?' } %>

                  </div>
                </div>

              </div>

          <% end %>
        </div>
        <br>
</div>
<%= link_to 'New Listado', new_listado_path, class:'btn btn-link' %>

trabajo/theprettystore/app/views/listados/new.html.erb
<h1>New Listado</h1>

<%= render 'form' %>

<%= link_to 'Back', listados_path, class:'btn btn-link' %>

trabajo/theprettystore/app/views/listados/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-6">
    <div class="thumbnail">
        <%= image_tag @listado.image.url%>
    </div>
  </div>
      <div class="col-md-6">
        <h3><%= @listado.name %></h3>
        <p><%= number_to_currency(@listado.price, :unit => " € ") %></p>
        <p><%= @listado.description %></p>
  </div>
</div>



<%= link_to 'Edit', edit_listado_path(@listado), class:'btn btn-link' %> |
<%= link_to 'Back', listados_path, class:'btn btn-link' %>

trabajo/theprettystore/app/views/pages/contacto.html.erb
<h1>Contacto</h1>

trabajo/theprettystore/app/views/pages/sobre.html.erb
<h1>Sobre</h1>